### ISSUE TITLE
Documentation for xs2a adapter. Build failures.

### ISSUE THREAD

**Issue by kristjank90** [adorsys/xs2a-adapter#289] opened 2019-11-28 13:33 UTC
Hi Team!

Thanks for your efforts in developing open-source XS2A adapter.  We are working on a mobile application and would like to integrate our prototype backend to banks open banking API-s. XS2A adapter is a solution which we are looking for as open source  integration solution. 

First - please if possible update the documentation of XS2A overall adapter architecture (modules) and best use case guidelines for implementation, as it would greatly benefit our further development efforts.

Secondly, we noticed a issue - while following the guidelines and running "mvn clean package" - the build fails with message: 
"[INFO] ------------------------------------------------------------------------
[ERROR] Failed to execute goal org.apache.maven.plugins:maven-surefire-plugin:2.12.4:test (default-test) on project xs2a-adapter-service-api: Execution default-test of goal org.apache.maven.plugins:maven-surefire-plugin:2.12.4:test failed: The forked VM terminated without saying properly goodbye. VM crash or System.exit called ? -> [Help 1]
"
We tried updating POM file and use newer surefire plugin - does not work. As workaround using SkipTests flags allows the build to succeed.

Thanks!

**Comment by artemsnisarenko** [comment] 2019-11-29 15:05
Hi kristjank90,
Thank you for taking interest in the project.
Regarding the build failure you got. Could you provide some context about your build environment? What maven version and jdk vendor/version do you have? It would be ideal if you could provide a small Dockerfile that reproduces the issue. I cannot reproduce it, even with `forkCount` greater than zero.

**Comment by kristjank90** [comment] 2019-12-01 11:25
Hi artemsnisarenko,

Details about environment. More information in DBG txt file:

> _PS C:\Dev\another\xs2a-adapter> mvn clean package -X
> 
> > Apache Maven 3.6.2 (40f52333136460af0dc0d7232c0dc0bcf0d9e117; 2019-08-27T18:06:16+03:00)
> > Maven home: C:\Program Files\Java\jdk-13.0.1\maven\bin\..
> > Java version: 13.0.1, vendor: Oracle Corporation, runtime: C:\Program Files\Java\jdk-13.0.1
> > Default locale: en_GB, platform encoding: Cp1252
> > OS name: "windows 10", version: "10.0", arch: "amd64", family: "windows"_
> > 

[DBG - xs2a Steps to error.txt](https://github.com/adorsys/xs2a-adapter/files/3908128/DBG.-.xs2a.Steps.to.error.txt)

With "mvn clean package -X -DskipTests" BUILD succeeds. I hope this helps. Thank you.

> Note: we also run it in macOS Mojave with latest Java and Maven. Same issues.

**Comment by artemsnisarenko** [comment] 2019-12-01 15:57
Looks like the error is caused by the jacoco plugin failing to instrument some code. It should be resolved by the plugin version upgrade https://github.com/adorsys/xs2a-adapter/pull/291.

**Comment by kristjank90** [comment] 2019-12-01 22:57
Seems to be working. All tests succeeded and build OK. Thanks!

**Closed** 2019-12-02 14:00 UTC
